import { FoodItem } from "./types";

export type BaseProduct = {
  id: string;
  name: string;
  category: "Nabiał i Jaja" | "Mięso i Ryby" | "Pieczywo i Zboża" | "Owoce i Warzywa" | "Orzechy i Nasiona" | "Napoje i Dodatki" | "Przekąski i Słodycze";
  kcalPer100g: number;
  proteinPer100g: number;
  fatPer100g: number;
  carbsPer100g: number;
  defaultGrams: number;
  unitName?: string; // np. "1 sztuka", "1 łyżka", "1 szklanka"
  unitGrams?: number;
};

export const FOOD_DATABASE: BaseProduct[] = [
  // Nabiał i Jaja
  {
    id: "p-jajko",
    name: "Jajko kurze (klasa M/L)",
    category: "Nabiał i Jaja",
    kcalPer100g: 143,
    proteinPer100g: 12.6,
    fatPer100g: 9.5,
    carbsPer100g: 0.7,
    defaultGrams: 110,
    unitName: "1 sztuka",
    unitGrams: 55,
  },
  {
    id: "p-twarog-chudy",
    name: "Twaróg chudy (0%)",
    category: "Nabiał i Jaja",
    kcalPer100g: 86,
    proteinPer100g: 18.0,
    fatPer100g: 0.5,
    carbsPer100g: 3.5,
    defaultGrams: 150,
    unitName: "1 opakowanie",
    unitGrams: 200,
  },
  {
    id: "p-twarog-poltlusty",
    name: "Twaróg półtłusty",
    category: "Nabiał i Jaja",
    kcalPer100g: 115,
    proteinPer100g: 16.5,
    fatPer100g: 4.0,
    carbsPer100g: 3.8,
    defaultGrams: 125,
    unitName: "1 opakowanie",
    unitGrams: 200,
  },
  {
    id: "p-skyr-naturalny",
    name: "Skyr naturalny (wysokobiałkowy)",
    category: "Nabiał i Jaja",
    kcalPer100g: 65,
    proteinPer100g: 12.0,
    fatPer100g: 0.2,
    carbsPer100g: 4.0,
    defaultGrams: 150,
    unitName: "1 kubek",
    unitGrams: 150,
  },
  {
    id: "p-skyr-waniliowy",
    name: "Skyr waniliowy",
    category: "Nabiał i Jaja",
    kcalPer100g: 82,
    proteinPer100g: 10.5,
    fatPer100g: 0.2,
    carbsPer100g: 9.5,
    defaultGrams: 150,
    unitName: "1 kubek",
    unitGrams: 150,
  },
  {
    id: "p-serek-wiejski",
    name: "Serek wiejski lekki (Cottage cheese)",
    category: "Nabiał i Jaja",
    kcalPer100g: 81,
    proteinPer100g: 11.0,
    fatPer100g: 3.0,
    carbsPer100g: 2.5,
    defaultGrams: 200,
    unitName: "1 opakowanie",
    unitGrams: 200,
  },
  {
    id: "p-mleko-2",
    name: "Mleko 2.0% świeże / UHT",
    category: "Nabiał i Jaja",
    kcalPer100g: 50,
    proteinPer100g: 3.3,
    fatPer100g: 2.0,
    carbsPer100g: 4.8,
    defaultGrams: 250,
    unitName: "1 szklanka",
    unitGrams: 250,
  },
  {
    id: "p-jogurt-grecki",
    name: "Jogurt grecki naturalny",
    category: "Nabiał i Jaja",
    kcalPer100g: 115,
    proteinPer100g: 7.0,
    fatPer100g: 8.0,
    carbsPer100g: 4.0,
    defaultGrams: 150,
    unitName: "1 porcja",
    unitGrams: 150,
  },
  {
    id: "p-mozzarella-light",
    name: "Ser Mozzarella light",
    category: "Nabiał i Jaja",
    kcalPer100g: 165,
    proteinPer100g: 20.0,
    fatPer100g: 8.5,
    carbsPer100g: 2.0,
    defaultGrams: 125,
    unitName: "1 kulka",
    unitGrams: 125,
  },
  {
    id: "p-ser-gouda",
    name: "Ser żółty Gouda",
    category: "Nabiał i Jaja",
    kcalPer100g: 356,
    proteinPer100g: 25.0,
    fatPer100g: 28.0,
    carbsPer100g: 0.1,
    defaultGrams: 30,
    unitName: "1 plaster",
    unitGrams: 20,
  },
  {
    id: "p-bialko-wpc",
    name: "Odżywka białkowa WPC (Whey Protein)",
    category: "Nabiał i Jaja",
    kcalPer100g: 395,
    proteinPer100g: 78.0,
    fatPer100g: 6.0,
    carbsPer100g: 7.0,
    defaultGrams: 30,
    unitName: "1 miarka",
    unitGrams: 30,
  },

  // Mięso i Ryby
  {
    id: "p-piers-kurczaka",
    name: "Pierś z kurczaka bez skóry",
    category: "Mięso i Ryby",
    kcalPer100g: 110,
    proteinPer100g: 22.5,
    fatPer100g: 1.3,
    carbsPer100g: 0.0,
    defaultGrams: 180,
    unitName: "1 filet",
    unitGrams: 180,
  },
  {
    id: "p-piers-indyka",
    name: "Pierś z indyka",
    category: "Mięso i Ryby",
    kcalPer100g: 104,
    proteinPer100g: 23.0,
    fatPer100g: 1.0,
    carbsPer100g: 0.0,
    defaultGrams: 180,
    unitName: "1 porcja",
    unitGrams: 180,
  },
  {
    id: "p-losos-swiezy",
    name: "Łosoś atlantycki świeży / pieczony",
    category: "Mięso i Ryby",
    kcalPer100g: 208,
    proteinPer100g: 20.0,
    fatPer100g: 14.0,
    carbsPer100g: 0.0,
    defaultGrams: 150,
    unitName: "1 dzwonko",
    unitGrams: 150,
  },
  {
    id: "p-tunczyk-wlasny",
    name: "Tuńczyk w sosie własnym (puszka)",
    category: "Mięso i Ryby",
    kcalPer100g: 110,
    proteinPer100g: 25.0,
    fatPer100g: 0.8,
    carbsPer100g: 0.0,
    defaultGrams: 130,
    unitName: "1 puszka po odsączeniu",
    unitGrams: 130,
  },
  {
    id: "p-schab-wieprzowy",
    name: "Schab wieprzowy bez kości",
    category: "Mięso i Ryby",
    kcalPer100g: 130,
    proteinPer100g: 22.0,
    fatPer100g: 4.5,
    carbsPer100g: 0.0,
    defaultGrams: 150,
    unitName: "1 kotlet",
    unitGrams: 140,
  },
  {
    id: "p-wolowina-mielona",
    name: "Mięso mielone wołowe chude (95/5)",
    category: "Mięso i Ryby",
    kcalPer100g: 137,
    proteinPer100g: 21.0,
    fatPer100g: 5.0,
    carbsPer100g: 0.0,
    defaultGrams: 150,
    unitName: "1 porcja",
    unitGrams: 150,
  },
  {
    id: "p-szynka-drobiowa",
    name: "Szynka z piersi kurczaka / indyka",
    category: "Mięso i Ryby",
    kcalPer100g: 95,
    proteinPer100g: 19.0,
    fatPer100g: 1.5,
    carbsPer100g: 1.0,
    defaultGrams: 40,
    unitName: "2 plastry",
    unitGrams: 40,
  },
  {
    id: "p-dorsz-filet",
    name: "Dorsz polędwica / filet",
    category: "Mięso i Ryby",
    kcalPer100g: 82,
    proteinPer100g: 18.0,
    fatPer100g: 0.7,
    carbsPer100g: 0.0,
    defaultGrams: 180,
    unitName: "1 porcja",
    unitGrams: 180,
  },

  // Pieczywo i Zboża
  {
    id: "p-chleb-zytni",
    name: "Chleb żytni 100% na zakwasie",
    category: "Pieczywo i Zboża",
    kcalPer100g: 225,
    proteinPer100g: 6.0,
    fatPer100g: 1.5,
    carbsPer100g: 45.0,
    defaultGrams: 70,
    unitName: "1 kromka",
    unitGrams: 35,
  },
  {
    id: "p-bulka-grahamka",
    name: "Bułka grahamka",
    category: "Pieczywo i Zboża",
    kcalPer100g: 255,
    proteinPer100g: 8.5,
    fatPer100g: 2.0,
    carbsPer100g: 50.0,
    defaultGrams: 70,
    unitName: "1 sztuka",
    unitGrams: 70,
  },
  {
    id: "p-platki-owsiane",
    name: "Płatki owsiane górskie",
    category: "Pieczywo i Zboża",
    kcalPer100g: 375,
    proteinPer100g: 13.5,
    fatPer100g: 7.0,
    carbsPer100g: 62.0,
    defaultGrams: 60,
    unitName: "1 porcja (6 łyżek)",
    unitGrams: 60,
  },
  {
    id: "p-ryz-basmati",
    name: "Ryż Basmati / Jaśminowy (suchy)",
    category: "Pieczywo i Zboża",
    kcalPer100g: 355,
    proteinPer100g: 7.5,
    fatPer100g: 0.8,
    carbsPer100g: 78.0,
    defaultGrams: 75,
    unitName: "1 woreczek",
    unitGrams: 100,
  },
  {
    id: "p-kasza-gryczana",
    name: "Kasza gryczana palona (sucha)",
    category: "Pieczywo i Zboża",
    kcalPer100g: 345,
    proteinPer100g: 12.0,
    fatPer100g: 3.0,
    carbsPer100g: 65.0,
    defaultGrams: 75,
    unitName: "1 woreczek",
    unitGrams: 100,
  },
  {
    id: "p-makaron-pelnoziarnisty",
    name: "Makaron pełnoziarnisty (suchy)",
    category: "Pieczywo i Zboża",
    kcalPer100g: 350,
    proteinPer100g: 13.0,
    fatPer100g: 2.5,
    carbsPer100g: 67.0,
    defaultGrams: 80,
    unitName: "1 porcja",
    unitGrams: 80,
  },
  {
    id: "p-ziemniaki",
    name: "Ziemniaki gotowane",
    category: "Pieczywo i Zboża",
    kcalPer100g: 77,
    proteinPer100g: 2.0,
    fatPer100g: 0.1,
    carbsPer100g: 17.5,
    defaultGrams: 250,
    unitName: "1 średni ziemniak",
    unitGrams: 90,
  },
  {
    id: "p-tortilla-wrap",
    name: "Tortilla wrap pszenna / pełnoziarnista",
    category: "Pieczywo i Zboża",
    kcalPer100g: 305,
    proteinPer100g: 8.0,
    fatPer100g: 6.5,
    carbsPer100g: 52.0,
    defaultGrams: 62,
    unitName: "1 placek",
    unitGrams: 62,
  },

  // Owoce i Warzywa
  {
    id: "p-banan",
    name: "Banan świeży (bez skórki)",
    category: "Owoce i Warzywa",
    kcalPer100g: 89,
    proteinPer100g: 1.1,
    fatPer100g: 0.3,
    carbsPer100g: 22.8,
    defaultGrams: 120,
    unitName: "1 średnia sztuka",
    unitGrams: 120,
  },
  {
    id: "p-jablko",
    name: "Jabłko świeże",
    category: "Owoce i Warzywa",
    kcalPer100g: 52,
    proteinPer100g: 0.3,
    fatPer100g: 0.2,
    carbsPer100g: 13.8,
    defaultGrams: 160,
    unitName: "1 średnie jabłko",
    unitGrams: 160,
  },
  {
    id: "p-borowki",
    name: "Borówki amerykańskie / Jagody",
    category: "Owoce i Warzywa",
    kcalPer100g: 57,
    proteinPer100g: 0.7,
    fatPer100g: 0.3,
    carbsPer100g: 14.5,
    defaultGrams: 125,
    unitName: "1 mała miseczka",
    unitGrams: 125,
  },
  {
    id: "p-truskawki",
    name: "Truskawki świeże",
    category: "Owoce i Warzywa",
    kcalPer100g: 32,
    proteinPer100g: 0.7,
    fatPer100g: 0.3,
    carbsPer100g: 7.7,
    defaultGrams: 200,
    unitName: "1 szklanka",
    unitGrams: 150,
  },
  {
    id: "p-awokado",
    name: "Awokado Hass",
    category: "Owoce i Warzywa",
    kcalPer100g: 160,
    proteinPer100g: 2.0,
    fatPer100g: 15.0,
    carbsPer100g: 8.5,
    defaultGrams: 70,
    unitName: "pół awokado",
    unitGrams: 70,
  },
  {
    id: "p-pomidor",
    name: "Pomidor malinowy",
    category: "Owoce i Warzywa",
    kcalPer100g: 18,
    proteinPer100g: 0.9,
    fatPer100g: 0.2,
    carbsPer100g: 3.9,
    defaultGrams: 150,
    unitName: "1 średnia sztuka",
    unitGrams: 150,
  },
  {
    id: "p-ogorek",
    name: "Ogórek zielony / gruntowy",
    category: "Owoce i Warzywa",
    kcalPer100g: 15,
    proteinPer100g: 0.7,
    fatPer100g: 0.1,
    carbsPer100g: 3.0,
    defaultGrams: 100,
    unitName: "1 sztuka",
    unitGrams: 120,
  },
  {
    id: "p-papryka",
    name: "Papryka czerwona",
    category: "Owoce i Warzywa",
    kcalPer100g: 31,
    proteinPer100g: 1.0,
    fatPer100g: 0.3,
    carbsPer100g: 6.0,
    defaultGrams: 140,
    unitName: "1 sztuka",
    unitGrams: 140,
  },
  {
    id: "p-brokul",
    name: "Brokuł gotowany na parze",
    category: "Owoce i Warzywa",
    kcalPer100g: 35,
    proteinPer100g: 2.8,
    fatPer100g: 0.4,
    carbsPer100g: 7.0,
    defaultGrams: 150,
    unitName: "pół brokuła",
    unitGrams: 200,
  },

  // Orzechy i Tłuszcze
  {
    id: "p-orzechy-nerkowca",
    name: "Orzechy nerkowca (Paczka/Porcja)",
    category: "Orzechy i Nasiona",
    kcalPer100g: 553,
    proteinPer100g: 18.2,
    fatPer100g: 43.8,
    carbsPer100g: 30.2,
    defaultGrams: 40,
    unitName: "1 garść (30g)",
    unitGrams: 30,
  },
  {
    id: "p-orzeszki-ziemne",
    name: "Orzeszki ziemne solone / prażone",
    category: "Orzechy i Nasiona",
    kcalPer100g: 590,
    proteinPer100g: 26.0,
    fatPer100g: 49.0,
    carbsPer100g: 16.0,
    defaultGrams: 50,
    unitName: "1 mała paczka (50g)",
    unitGrams: 50,
  },
  {
    id: "p-orzechy-wloskie",
    name: "Orzechy włoskie łuskane",
    category: "Orzechy i Nasiona",
    kcalPer100g: 654,
    proteinPer100g: 15.2,
    fatPer100g: 65.2,
    carbsPer100g: 13.7,
    defaultGrams: 30,
    unitName: "1 garść (30g)",
    unitGrams: 30,
  },
  {
    id: "p-maslo-orzechowe",
    name: "Masło orzechowe 100% (Peanut Butter)",
    category: "Orzechy i Nasiona",
    kcalPer100g: 595,
    proteinPer100g: 27.0,
    fatPer100g: 47.0,
    carbsPer100g: 13.0,
    defaultGrams: 25,
    unitName: "1 czubata łyżka (25g)",
    unitGrams: 25,
  },
  {
    id: "p-oliwa-z-oliwek",
    name: "Oliwa z oliwek Extra Virgin",
    category: "Orzechy i Nasiona",
    kcalPer100g: 884,
    proteinPer100g: 0.0,
    fatPer100g: 100.0,
    carbsPer100g: 0.0,
    defaultGrams: 10,
    unitName: "1 łyżka (10g)",
    unitGrams: 10,
  },
  {
    id: "p-maslo-82",
    name: "Masło ekstra 82%",
    category: "Orzechy i Nasiona",
    kcalPer100g: 742,
    proteinPer100g: 0.7,
    fatPer100g: 82.0,
    carbsPer100g: 0.7,
    defaultGrams: 10,
    unitName: "1 porcja na kromkę (10g)",
    unitGrams: 10,
  },

  // Napoje i Dodatki
  {
    id: "p-herbata-czarna",
    name: "Herbata czarna / zielona (bez cukru)",
    category: "Napoje i Dodatki",
    kcalPer100g: 1,
    proteinPer100g: 0.1,
    fatPer100g: 0.0,
    carbsPer100g: 0.2,
    defaultGrams: 250,
    unitName: "1 kubek (250ml)",
    unitGrams: 250,
  },
  {
    id: "p-cukier-bialy",
    name: "Cukier biały kryształ",
    category: "Napoje i Dodatki",
    kcalPer100g: 400,
    proteinPer100g: 0.0,
    fatPer100g: 0.0,
    carbsPer100g: 100.0,
    defaultGrams: 10,
    unitName: "1 łyżeczka (5g)",
    unitGrams: 5,
  },
  {
    id: "p-miod-pszczeli",
    name: "Miód pszczeli naturalny",
    category: "Napoje i Dodatki",
    kcalPer100g: 320,
    proteinPer100g: 0.3,
    fatPer100g: 0.0,
    carbsPer100g: 80.0,
    defaultGrams: 15,
    unitName: "1 łyżka (15g)",
    unitGrams: 15,
  },
  {
    id: "p-kawa-z-mlekiem",
    name: "Kawa z mlekiem 2% (bez cukru)",
    category: "Napoje i Dodatki",
    kcalPer100g: 22,
    proteinPer100g: 1.4,
    fatPer100g: 0.8,
    carbsPer100g: 2.1,
    defaultGrams: 250,
    unitName: "1 kubek (250ml)",
    unitGrams: 250,
  },
  {
    id: "p-czekolada-gorzka",
    name: "Czekolada gorzka 70% kakao",
    category: "Przekąski i Słodycze",
    kcalPer100g: 580,
    proteinPer100g: 7.8,
    fatPer100g: 43.0,
    carbsPer100g: 36.0,
    defaultGrams: 20,
    unitName: "2 kostki (20g)",
    unitGrams: 20,
  },
];

export function calculateMacros(product: BaseProduct, grams: number): {
  kcal: number;
  protein: number;
  fat: number;
  carbs: number;
} {
  const factor = grams / 100;
  return {
    kcal: Math.round(product.kcalPer100g * factor),
    protein: Math.round(product.proteinPer100g * factor * 10) / 10,
    fat: Math.round(product.fatPer100g * factor * 10) / 10,
    carbs: Math.round(product.carbsPer100g * factor * 10) / 10,
  };
}

export function searchLocalProducts(query: string): BaseProduct[] {
  const q = query.trim().toLowerCase();
  if (!q) return FOOD_DATABASE.slice(0, 15);
  return FOOD_DATABASE.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}
